# Generated by Django 4.0.4 on 2023-10-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
    ]
