COUNTRIES = {
    "af": {"Afghanistan", "Pashto", "Dari", "Afghan", "Ashraf Ghani", "Taliban", "Hibatullah Akhundzada", "Kabul", "Herat", "Mazari Sharif", "Kandahar", "Moby Group", "Afghan Telecom", "Afghan Wireless","Azizi Bank","Etisalat Afghanistan","East Texas Medical Center","Roshan","Awcc"},
    "ax": {"Akrotiri", "Episkopi Cantonment ", "Robert J. THOMSON"},
    "al": {"Albania", "Albanian", "Tirana", "Edi Rama", "leke", "Southeastern Europe", "Adriatic Sea", "Ionian Sea", "Balfin Group", "Albtelecom Albania", "Telekom Albania", "Raiffeisen Bank Albania", "Epoka University", "National Food Authority", "Brunes", "Albanian Center For Economic Research (Acer)", },
    "dz": {"Algeria", "Arabic", "Algiers", "Abdelmadjid Tebboune", "dinars", "Northern Africa", "Mediterranean Sea", "Morocco", "Tunisia", "Abdelmadjid TEBBOUNE", "Council of the Nation", "National People's Assembly", },
    "as": {"American Samoa", "Pago Pago", "Oceania", "Samoan", },
    "ad": {"Andorra", "Catalan", "Andorran", "Xavier Espot Zamora"},
    "ao": {"Angola", "Portuguese", "Angolan", "João Lourenço"},
    "ai": {"Anguilla"},
    "ag": {"Antigua and Barbuda", "English", "Antiguan and Barbudan", "Gaston Browne"},
    "ar": {"Argentina", "Spanish", "Argentinian", "Alberto Fernández"},
    "am": {"Armenia", "Armenian", "Yerevan", "Nikol Pashinyan"},
    "aw": {"Aruba", "Dutch", "Aruban", "Evelyn Wever-Croes"},
    "au": {"Australia", "English", "Australian", "Scott Morrison"},
    "at": {"Austria", "German", "Austrian", "Alexander Schallenberg"},
    "az": {"Azerbaijan", "Azerbaijani", "Baku", "Ilham Aliyev"},
    "bh": {"Bahrain", "Arabic", "Bahraini", "Hamad bin Isa Al Khalifa"},
    "bd": {"Bangladesh", "Bengali", "Bangladeshi", "Sheikh Hasina"},
    "bb": {"Barbados", "English", "Barbadian", "Mia Mottley"},
    "by": {"Belarus", "Belarusian", "Minsk", "Alexander Lukashenko"},
    "be": {"Belgium", "Dutch, French, German", "Belgian", "Alexander De Croo"},
    "bz": {"Belize", "English", "Belizean", "Johnny Briceño"},
    "bj": {"Benin", "French", "Beninese", "Patrice Talon"},
    "bm": {"Bermuda"},
    "bt": {"Bhutan", "Dzongkha", "Bhutanese", "Lotay Tshering"},
    "bo": {"Bolivia", "Spanish", "Bolivian", "Luis Arce"},
    "ba": {"Bosnia and Herzegovina", "Bosnian, Croatian, Serbian", "Bosnian", "Milorad Dodik"},
    "bw": {"Botswana", "English, Tswana", "Motswana", "Mokgweetsi Masisi"},
    "br": {"Brazil", "Portuguese", "Brazilian", "Jair Bolsonaro"},
    "io": {"British Indian Ocean Territory"},
    "vg": {"British Virgin Islands"},
    "bn": {"Brunei", "Malay", "Bruneian", "Hassanal Bolkiah"},
    "bg": {"Bulgaria", "Bulgarian", "Sofia", "Stefan Yanev"},
    "bf": {"Burkina Faso", "French", "Burkinabé", "Paul-Henri Sandaogo Damiba"},
    "bi": {"Burundi", "Kirundi, French, English", "Burundian", "Évariste Ndayishimiye"},
    "cv": {"Cabo Verde", "Portuguese", "Cape Verdean", "José Maria Neves"},
    "kh": {"Cambodia", "Khmer", "Cambodian", "Hun Sen"},
    "cm": {"Cameroon", "English, French", "Cameroonian", "Paul Biya"},
    "ca": {"Canada", "English, French", "Canadian", "Justin Trudeau"},
    "ky": {"Cayman Islands"},
    "cf": {"Central African Republic", "French, Sango", "Central African", "Faustin-Archange Touadéra"},
    "td": {"Chad", "French, Arabic", "Chadian", "Mahamat Déby"},
    "cl": {"Chile", "Spanish", "Chilean", "Sebastián Piñera"},
    "cn": {"China", "Mandarin", "Chinese", "Xi Jinping"},
    "cx": {"Christmas Island"},
    "cc": {"Cocos Islands"},
    "co": {"Colombia", "Spanish", "Colombian", "Iván Duque Márquez"},
    "km": {"Comoros", "Comorian, Arabic, French", "Comoran", "Azali Assoumani"},
    "ck": {"Cook Islands", "English, Cook Islands Māori", "Cook Islander", "Mark Brown"},
    "cr": {"Costa Rica", "Spanish", "Costa Rican", "Carlos Alvarado Quesada"},
    "ci": {"Côte d'Ivoire", "French", "Ivorian", "Alassane Ouattara"},
    "hr": {"Croatia", "Croatian", "Croatian", "Andrej Plenković"},
    "cu": {"Cuba", "Spanish", "Cuban", "Miguel Díaz-Canel"},
    "cw": {"Curaçao", "Dutch, Papiamento", "Curaçaoan", "Eugene Rhuggenaath"},
    "cy": {"Cyprus", "Greek, Turkish", "Cypriot", "Nicos Anastasiades"},
    "cz": {"Czechia", "Czech", "Czech", "Miloš Zeman"},
    "cd": {"Democratic Republic of the Congo", "French", "Congolese", "Félix Tshisekedi"},
    "dk": {"Denmark", "Danish", "Danish", "Mette Frederiksen"},
    "dx": {"Dhekelia"},
    "dj": {"Djibouti", "French, Arabic", "Djiboutian", "Ismail Omar Guelleh"},
    "dm": {"Dominica", "English", "Dominican", "Charles Savarin"},
    "do": {"Dominican Republic", "Spanish", "Dominican", "Luis Abinader"},
    "ec": {"Ecuador", "Spanish", "Ecuadorian", "Guillermo Lasso"},
    "eg": {"Egypt", "Arabic", "Egyptian", "Abdel Fattah el-Sisi"},
    "sv": {"El Salvador", "Spanish", "Salvadoran", "Nayib Bukele"},
    "gq": {"Equatorial Guinea", "Spanish, French, Portuguese", "Equatorial Guinean", "Teodoro Obiang Nguema Mbasogo"},
    "er": {"Eritrea", "Tigrinya, Arabic, English", "Eritrean", "Isaias Afwerki"},
    "ee": {"Estonia", "Estonian", "Estonian", "Kersti Kaljulaid"},
    "et": {"Ethiopia", "Amharic", "Ethiopian", "Abiy Ahmed"},
    "fk": {"Falkland Islands", "English", "Falkland Islander", "Nigel Phillips"},
    "fo": {"Faroe Islands", "Faroese, Danish", "Faroese", "Bárður á Steig Nielsen"},
    "fm": {"Federated States of Micronesia", "English", "Micronesian", "David W. Panuelo"},
    "fj": {"Fiji", "English, Fijian, Hindi", "Fijian", "Josaia Voreqe Bainimarama"},
    "fi": {"Finland", "Finnish, Swedish", "Finnish", "Sauli Väinämö Niinistö"},
    "fr": {"France", "French", "French", "Emmanuel Macron"},
    "gf": {"French Guiana", "French", "Guianan", "Rodolphe Alexandre"},
    "pf": {"French Polynesia", "French, Tahitian", "Tahitian", "Édouard Fritch"},
    "tf": {"French Southern and Antarctic Lands"},
    "ga": {"Gabon", "French", "Gabonese", "Ali Bongo Ondimba"},
    "ge": {"Georgia", "Georgian", "Georgian", "Salome Zourabichvili"},
    "de": {"Germany", "German", "German", "Angela Merkel"},
    "gh": {"Ghana", "English", "Ghanaian", "Nana Akufo-Addo"},
    "gi": {"Gibraltar", "English", "Gibraltarian", "Fabian Picardo"},
    "gr": {"Greece", "Greek", "Greek", "Kyriakos Mitsotakis"},
    "gl": {"Greenland", "Greenlandic, Danish", "Greenlandic", "Mute Egede"},
    "gd": {"Grenada", "English", "Grenadian", "Keith Mitchell"},
    "gp": {"Guadeloupe", "French", "Guadeloupean", "Ary Chalus"},
    "gu": {"Guam", "English, Chamorro", "Guamanian", "Lou Leon Guerrero"},
    "gt": {"Guatemala", "Spanish", "Guatemalan", "Alejandro Giammattei"},
    "gg": {"Guernsey", "English, French, Norman-French", "Channel Islander", "Peter Ferbrache"},
    "gn": {"Guinea", "French", "Guinean", "Alpha Condé"},
    "gw": {"Guinea-Bissau", "Portuguese", "Guinea-Bissauan", "Umaro Sissoco Embaló"},
    "gy": {"Guyana", "English", "Guyanese", "Irfaan Ali"},
    "ht": {"Haiti", "French, Haitian Creole", "Haitian", "Ariel Henry"},
    "hn": {"Honduras", "Spanish", "Honduran", "Juan Orlando Hernández"},
    "hk": {"Hong Kong", "Chinese, English", "Hongkonger", "Carrie Lam"},
    "hu": {"Hungary", "Hungarian", "Hungarian", "Viktor Orbán"},
    "is": {"Iceland", "Icelandic", "Icelander", "Katrin Jakobsdottir"},
    "in": {"India", "Hindi, English", "Indian", "Narendra Modi"},
    "id": {"Indonesia", "Indonesian", "Indonesian", "Joko Widodo"},
    "ir": {"Iran", "Persian", "Iranian", "Ebrahim Raisi"},
    "iq": {"Iraq", "Arabic, Kurdish", "Iraqi", "Barham Salih"},
    "ie": {"Ireland", "Irish, English", "Irish", "Michael D. Higgins"},
    "im": {"Isle of Man", "English, Manx", "Manx", "Howard Quayle"},
    "il": {"Israel", "Hebrew", "Israeli", "Naftali Bennett", "Benjamin Netanyahu", "Hamas", "Gaza", "IDF", "Israeli Defense Force", "Biden"},
    "it": {"Italy", "Italian", "Italian", "Mario Draghi"},
    "jm": {"Jamaica", "English, Jamaican Patois", "Jamaican", "Andrew Holness"},
    "jp": {"Japan", "Japanese", "Japanese", "Yoshihide Suga"},
    "je": {"Jersey", "English, French, Norman-French", "Channel Islander", "John Le Fondré"},
    "jo": {"Jordan", "Arabic", "Jordanian", "Abdulah II of Jordan"},
    "kz": {"Kazakhstan", "Kazakh, Russian", "Kazakh", "Kassym-Jomart Tokayev"},
    "ke": {"Kenya", "Swahili, English", "Kenyan", "Uhuru Kenyatta"},
    "ki": {"Kiribati", "English, Gilbertese", "I-Kiribati", "Taneti Maamau"},
    "xk": {"Kosovo", "Albanian, Serbian", "Kosovar", "Vjosa Osmani"},
    "kw": {"Kuwait", "Arabic", "Kuwaiti", "Nawaf Al-Ahmad Al-Jaber Al-Sabah"},
    "kg": {"Kyrgyzstan", "Kyrgyz, Russian", "Kyrgyzstani", "Sadyr Japarov"},
    "la": {"Laos", "Lao", "Lao", "Thongloun Sisoulith"},
    "lv": {"Latvia", "Latvian", "Latvian", "Egils Levits"},
    "lb": {"Lebanon", "Arabic, French", "Lebanese", "Michel Aoun"},
    "ls": {"Lesotho", "English, Sesotho", "Mosotho", "Majoro Tom"},
    "lr": {"Liberia", "English", "Liberian", "George Weah"},
    "ly": {"Libya", "Arabic", "Libyan", "Abdul Hamid Dbeibeh"},
    "li": {"Liechtenstein", "German", "Liechtensteiner", "Adrian Hasler"},
    "lt": {"Lithuania", "Lithuanian", "Lithuanian", "Gitanas Nausėda"},
    "lu": {"Luxembourg", "Luxembourgish, French, German", "Luxembourger", "Xavier Bettel"},
    "mo": {"Macau", "Chinese, Portuguese", "Macanese", "Ho Iat Seng"},
    "mk": {"Macedonia", "Macedonian, Albanian", "Macedonian", "Stevce Jakimovski"},
    "mg": {"Madagascar", "Malagasy, French", "Malagasy", "Andry Rajoelina"},
    "mw": {"Malawi", "Chichewa, English", "Malawian", "Lazarus Chakwera"},
    "my": {"Malaysia", "Malay", "Malaysian", "Ismail Sabri Yaakob"},
    "mv": {"Maldives", "Dhivehi", "Maldivian", "Ibrahim Mohamed Solih"},
    "ml": {"Mali", "French", "Malian", "Assimi Goïta"},
    "mt": {"Malta", "Maltese, English", "Maltese", "Robert Abela"},
    "mh": {"Marshall Islands", "English, Marshallese", "Marshallese", "David Kabua"},
    "mq": {"Martinique", "French", "Martinican", "Alfred Marie-Jeanne"},
    "mr": {"Mauritania", "Arabic", "Mauritanian", "Mohamed Ould Ghazouani"},
    "mu": {"Mauritius", "English, French, Mauritian Creole", "Mauritian", "Prithvirajsing Roopun"},
    "yt": {"Mayotte", "French", "Mahoran", "Azali Assoumani"},
    "mx": {"Mexico", "Spanish", "Mexican", "Andrés Manuel López Obrador"},
    "md": {"Moldova", "Romanian", "Moldovan", "Maia Sandu"},
    "mc": {"Monaco", "French", "Monacan", "Albert II of Monaco"},
    "mn": {"Mongolia", "Mongolian", "Mongolian", "Ukhnaagiin Khürelsükh"},
    "me": {"Montenegro", "Montenegrin, Serbian", "Montenegrin", "Milo Đukanović"},
    "ms": {"Montserrat", "English", "Montserratian", "Joseph E. Farrell"},
    "ma": {"Morocco", "Arabic, Berber", "Moroccan", "Mohammed VI of Morocco"},
    "mz": {"Mozambique", "Portuguese", "Mozambican", "Filipe Nyusi"},
    "mm": {"Myanmar", "Burmese", "Myanmar", "Win Myint"},
    "na": {"Namibia", "English, Afrikaans", "Namibian", "Hage Geingob"},
    "nr": {"Nauru", "Nauruan, English", "Nauruan", "Cyril Abé"},
    "np": {"Nepal", "Nepali", "Nepali", "Sher Bahadur Deuba"},
    "nl": {"Netherlands", "Dutch", "Dutch", "Mark Rutte"},
    "nc": {"New Caledonia", "French", "New Caledonian", "Sonia Backès"},
    "nz": {"New Zealand", "English, Māori", "New Zealander", "Jacinda Ardern"},
    "ni": {"Nicaragua", "Spanish", "Nicaraguan", "Daniel Ortega"},
    "ne": {"Niger", "French", "Nigerien", "Mohamed Bazoum"},
    "ng": {"Nigeria", "English", "Nigerian", "Muhammadu Buhari"},
    "nu": {"Niue", "Niuean, English", "Niuean", "Dalton Tagelagi"},
    "nf": {"Norfolk Island"},
    "kp": {"North Korea", "Korean", "North Korean", "Kim Jong-un"},
    "mp": {"Northern Mariana Islands", "English, Chamorro", "Chamorro", "Ralph Torres"},
    "no": {"Norway", "Norwegian", "Norwegian", "Erna Solberg"},
    "om": {"Oman", "Arabic", "Omani", "Haitham bin Tariq Al Said"},
    "pk": {"Pakistan", "Urdu, English", "Pakistani", "Imran Khan"},
    "pw": {"Palau", "Palauan, English", "Palauan", "Surangel Whipps Jr."},
    "ps": {"Palestine", "Arabic", "Palestinian", "Mahmoud Abbas", "Hamas", "Sinuar", "Gaza"},
    "pa": {"Panama", "Spanish", "Panamanian", "Laurentino Cortizo"},
    "pg": {"Papua New Guinea", "English, Tok Pisin, Hiri Motu", "Papua New Guinean", "James Marape"},
    "pf": {"Paracel Islands"},
    "py": {"Paraguay", "Spanish, Guaraní", "Paraguayan", "Mario Abdo Benítez"},
    "pe": {"Peru", "Spanish, Quechua, Aymara", "Peruvian", "Pedro Castillo"},
    "ph": {"Philippines", "Filipino, English", "Filipino", "Rodrigo Duterte"},
    "pn": {"Pitcairn Islands", "English, Pitkern", "Pitcairn Islander", "Charlene Warren-Peu"},
    "pl": {"Poland", "Polish", "Polish", "Andrzej Duda"},
    "pt": {"Portugal", "Portuguese", "Portuguese", "Marcelo Rebelo de Sousa"},
    "pr": {"Puerto Rico", "Spanish, English", "Puerto Rican", "Pedro Pierluisi"},
    "qa": {"Qatar", "Arabic", "Qatari", "Tamim bin Hamad Al Thani"},
    "cg": {"Republic of Congo", "French", "Congolese", "Denis Sassou Nguesso"},
    "re": {"Reunion", "French", "Réunionese", "Ericka Bareigts"},
    "ro": {"Romania", "Romanian", "Romanian", "Klaus Iohannis"},
    "ru": {"Russia", "Russian", "Russian", "Vladimir Putin"},
    "rw": {"Rwanda", "Kinyarwanda, French, English", "Rwandan", "Paul Kagame"},
    "bl": {"Saint Barthelemy", "French", "Saint Barthélemy"},
    "kn": {"Saint Kitts and Nevis", "English", "Kittitian and Nevisian", "Timothy Harris"},
    "lc": {"Saint Lucia", "English, French Creole", "Saint Lucian", "Allen Chastanet"},
    "mf": {"Saint Martin", "French", "Saint-Martinoise"},
    "pm": {"Saint Pierre and Miquelon", "French", "Saint-Pierrais"},
    "vc": {"Saint Vincent and the Grenadines", "English", "Saint Vincentian", "Ralph Gonsalves"},
    "ws": {"Samoa", "Samoan, English", "Samoan", "Tuilaepa Aiono Sailele Malielegaoi"},
    "sm": {"San Marino", "Italian", "Sammarinese", "Marino Riccardi"},
    "st": {"Sao Tome and Principe", "Portuguese", "São Toméan", "Evaristo Carvalho"},
    "sa": {"Saudi Arabia", "Arabic", "Saudi Arabian", "Salman bin Abdulaziz Al Saud"},
    "sn": {"Senegal", "French", "Senegalese", "Macky Sall"},
    "rs": {"Serbia", "Serbian", "Serbian", "Aleksandar Vučić"},
    "sc": {"Seychelles", "Seychellois Creole, French, English", "Seychellois", "Wavel Ramkalawan"},
    "sl": {"Sierra Leone", "English", "Sierra Leonean", "Julius Maada Bio"},
    "sg": {"Singapore", "English, Malay, Mandarin, Tamil", "Singaporean", "Halimah Yacob"},
    "sx": {"Sint Maarten", "Dutch, English", "Sint Maartener", "Eugene Holiday"},
    "sk": {"Slovakia", "Slovak", "Slovak", "Zuzana Čaputová"},
    "si": {"Slovenia", "Slovenian", "Slovenian", "Borut Pahor"},
    "sb": {"Solomon Islands", "English", "Solomon Islander", "Manasseh Sogavare"},
    "so": {"Somalia", "Somali, Arabic", "Somali", "Mohamed Abdullahi Mohamed"},
    "za": {"South Africa", "Zulu, Xhosa, Afrikaans, English", "South African", "Cyril Ramaphosa"},
    "gs": {"South Georgia and South Sandwich Islands"},
    "kr": {"South Korea", "Korean", "South Korean", "Moon Jae-in"},
    "ss": {"South Sudan", "English", "South Sudanese", "Salva Kiir Mayardit"},
    "es": {"Spain", "Spanish", "Spanish", "Pedro Sánchez"},
    "ps": {"Spratly Islands"},
    "lk": {"Sri Lanka", "Sinhala, Tamil, English", "Sri Lankan", "Gotabaya Rajapaksa"},
    "sd": {"Sudan", "Arabic, English", "Sudanese", "Abdalla Hamdok"},
    "sr": {"Suriname", "Dutch", "Surinamese", "Chan Santokhi"},
    "sj": {"Svalbard", "Norwegian", "Svalbardian"},
    "sz": {"Swaziland", "Swazi, English", "Swazi", "Mswati III"},
    "se": {"Sweden", "Swedish", "Swedish", "Stefan Löfven"},
    "ch": {"Switzerland", "German, French, Italian, Romansh", "Swiss", "Guy Parmelin"},
    "sy": {"Syria", "Arabic", "Syrian", "Bashar al-Assad"},
    "tw": {"Taiwan", "Mandarin", "Taiwanese", "Tsai Ing-wen"},
    "tj": {"Tajikistan", "Tajik", "Tajikistani", "Emomali Rahmon"},
    "tz": {"Tanzania", "Swahili, English", "Tanzanian", "Samia Suluhu Hassan"},
    "th": {"Thailand", "Thai", "Thai", "Prayuth Chan-o-cha"},
    "bs": {"The Bahamas", "English", "Bahamian", "Hubert Minnis"},
    "gm": {"The Gambia", "English", "Gambian", "Adama Barrow"},
    "tl": {"Timor-Leste", "Portuguese, Tetum", "Timorese", "Francisco Guterres"},
    "tg": {"Togo", "French", "Togolese", "Faure Gnassingbé"},
    "tk": {"Tokelau", "Tokelauan, English", "Tokelauan"},
    "to": {"Tonga", "Tongan, English", "Tongan", "Pohiva Tu'i'onetoa"},
    "tt": {"Trinidad and Tobago", "English", "Trinidadian and Tobagonian", "Paula-Mae Weekes"},
    "tn": {"Tunisia", "Arabic", "Tunisian", "Kais Saied"},
    "tr": {"Turkey", "Turkish", "Turkish", "Recep Tayyip Erdoğan"},
    "tm": {"Turkmenistan", "Turkmen", "Turkmen", "Gurbanguly Berdimuhamedow"},
    "tc": {"Turks and Caicos Islands"},
    "tv": {"Tuvalu", "Tuvaluan, English", "Tuvaluan", "Kausea Natano"},
    "vi": {"U.S. Virgin Islands"},
    "ug": {"Uganda", "English, Swahili", "Ugandan", "Yoweri Museveni"},
    "ua": {"Ukraine", "Ukrainian, Russian", "Ukrainian", "Volodymyr Zelenskyy"},
    "ae": {"United Arab Emirates", "Arabic", "Emirati", "Khalifa bin Zayed Al Nahyan"},
    "gb": {"United Kingdom", "English", "British", "Boris Johnson"},
    "us": {"United States", "English", "American", "Joe Biden", "Biden", "Democrats", "Republicans", "Republican", "Democrat", "Washington", "White House", "D.C.", "DC", "District of Columbia", "Congress", "Senate",},
    "uy": {"Uruguay", "Spanish", "Uruguayan", "Luis Lacalle Pou"},
    "uz": {"Uzbekistan", "Uzbek, Karakalpak", "Uzbek", "Shavkat Mirziyoyev"},
    "vu": {"Vanuatu", "Bislama, English, French", "Vanuatuan", "Tallis Obed Moses"},
    "va": {"Vatican City", "Italian, Latin", "Vatican", "Pope Francis"},
    "ve": {"Venezuela", "Spanish", "Venezuelan", "Nicolás Maduro"},
    "vn": {"Vietnam", "Vietnamese", "Vietnamese", "Nguyen Xuan Phuc"},
    "wf": {"Wallis and Futuna", "French, Wallisian, Futunan", "Wallisian and Futunan"},
    "eh": {"Western Sahara", "Arabic, Berber", "Sahrawi", "Brahim Ghali"},
    "ye": {"Yemen", "Arabic", "Yemeni", "Abdrabbuh Mansur Hadi"},
    "zm": {"Zambia", "English", "Zambian", "Hakainde Hichilema"},
    "zw": {"Zimbabwe", "English, Chewa, Chibarwe, Kalanga, Koisan, Nambya, Ndau, Shangani, Sotho, Tonga, Tswana, Venda, Xhosa", "Zimbabwean", "Emmerson Mnangagwa"}
}