NOTWORDS = {
    'is', 'am', 'are', 'was', 'were', 'be', 'being', 'been',
    'have', 'has', 'had', 'do', 'does', 'did', 'can', 'could',
    'will', 'would', 'shall', 'should', 'may', 'might', 'must',
    'if', 'because', 'when', 'where', 'while', 'before', 'after',
    'though', 'although', 'but', 'and', 'or', 'not', 'for', 'nor',
    'so', 'yet', 'to', 'with', 'at', 'by', 'from', 'into', 'on',
    'onto', 'of', 'off', 'over', 'under', 'through', 'above',
    'below', 'up', 'down', 'in', 'out', 'between', 'among',
    'throughout', 'around', 'near', 'far', 'here', 'there',
    'now', 'then', 'always', 'never', 'sometimes', 'often',
    'rarely', 'seldom', 'once', 'twice', 'again', 'soon',
    'well', 'better', 'best', 'worse', 'worst', 'more', 'most',
    'less', 'least', 'sooner', 'later', 'early', 'late', 'upstairs',
    'downstairs', 'today', 'tonight', 'tomorrow', 'yesterday',
    'nowadays', 'everywhere', 'nowhere', 'anywhere', 'somewhere',
    'along', 'away', 'back', 'forward', 'here', 'there', 'now', 'then',
    'soon', 'early', 'late', 'right', 'left', 'up', 'down', 'inside',
    'outside', 'somehow', 'anyhow', 'anyway', 'everyhow', 'however',
    'nevertheless', 'furthermore', 'moreover', 'meanwhile', 'therefore',
    'consequently', 'accordingly', 'hence', 'thus', 'otherwise',
    'nevertheless', 'nonetheless', 'instead', 'indeed', 'besides',
    'furthermore', 'henceforth', 'whenever', 'wherever', 'whichever',
    'whoever', 'whatever', 'however', 'whenever', 'until', 'unless',
    'once', 'twice', 'thrice', 'always', 'never', 'sometimes', 'often',
    'rarely', 'seldom', 'soon', 'nowadays', 'today', 'tonight',
    'tomorrow', 'yesterday', 'immediately', 'eventually', 'recently',
    'finally', 'already', 'just', 'still', 'yet', 'almost', 'even',
    'only', 'again', 'too', 'very', 'so', 'such', 'rather', 'quite',
    'more', 'most', 'less', 'least', 'too', 'enough', 'very', 'much',
    'very', 'almost', 'well', 'badly', 'best', 'better', 'worse',
    'worst', 'least', 'moreover', 'furthermore', 'however', 'therefore',
    'otherwise', 'instead', 'nevertheless', 'nonetheless', 'meanwhile',
    'all', 'the', 'days', 'kids', 'area','thing', 'stuff', 'item', 'stuff', 'factor', 'element', 'aspect', 
    'aspect', 'point', 'case', 'instance', 'factor', 'situation', 
    'circumstance', 'condition', 'event', 'occurrence', 'occasion', 
    'detail', 'particular', 'aspect', 'way', 'manner', 'method', 
    'mode', 'style', 'means', 'process', 'procedure', 'approach', 
    'technique', 'system', 'strategy', 'way', 'means', 'manner', 
    'mode', 'method', 'system', 'process', 'procedure', 'approach', 
    'technique', 'way', 'manner', 'mode', 'style', 'method', 'system', 
    'procedure', 'process', 'approach', 'technique', 'way', 'means', 
    'manner', 'mode', 'method', 'style', 'approach', 'technique', 
    'system', 'procedure', 'process', 'way', 'manner', 'mode', 'style', 
    'method', 'means', 'technique', 'procedure', 'system', 'way', 
    'manner', 'mode', 'style', 'method', 'means', 'approach', 
    'technique', 'system', 'procedure', 'way', 'manner', 'mode', 
    'style', 'method', 'means', 'approach', 'technique', 'system', 
    'procedure', 'process', 'way', 'manner', 'mode', 'style', 
    'method', 'means', 'technique', 'approach', 'system', 'procedure', 'controlled', 'project',
    'role'
}