RELIABLE = {
    # Tech News
    "TechCrunch",
    "Ars Technica",
    "Wired",
    "The Verge",
    "CNET",
    "Mashable",
    "TechRadar",
    "Gizmodo",
    "ZDNet",
    "Engadget",
    
    # Political News
    "The New York Times - Politics",
    "The New York Times",
    "TNYT",
    "CNN Politics",
    "CNN",
    "Central National News",
    "BBC News - Politics",
    "BBC News",
    "BBC",
    "The Washington Post - Politics",
    "The Washington Post",
    "TWP",
    "Reuters - Politics",
    "Reuters",
    "NPR Politics",
    "NPR",
    "Politico",
    "The Guardian - Politics",
    "The Guardian",
    "National Review",
    
    # Sports News
    "ESPN",
    "CBS Sports",
    "CBS",
    "CBS News",
    "Bleacher Report",
    "Yahoo Sports",
    "BBC Sport",
    "Sports Illustrated",
    "NBA.com",
    "NFL.com",
    "MLB.com",
    "Sky Sports",
    
    # Celebrity and Entertainment News
    "E! Online",
    "People",
    "Entertainment Tonight",
    "Us Weekly",
    "TMZ",
    "Variety",
    "The Hollywood Reporter",
    "Deadline",
    "Access Hollywood",
    "Cosmopolitan - Entertainment",
    "Bloomberg",
    "Financial Times",
    "ESPN Cric Info",
    "UN News",
    "Global News",
    "Associated Press",
    "Associated Press News",
    "AP",
    "AP News",
    "ScienceAlert",
    "Universe Today",
    "Esa.int",
    "Moneycontrol",
    "Aviation Week",
    "Space.com",
    "Livemint",
}

PRIME = {
    "AP",
    "AP News",
    "CBS",
    "CBS News",
    "CNN",
    "The New York Times - Politics",
    "The New York Times",
    "TNYT",
    "TNYT News",
    "CNN Politics",
    "CNN",
    "cnn"
    "CNN News",
    "Central National News",
    "BBC News - Politics",
    "BBC News",
    "BBC",
    "The Washington Post - Politics",
    "The Washington Post",
    "TWP",
    "Reuters - Politics",
    "Reuters",
    "NPR Politics",
    "NPR",
    "The Guardian - Politics",
    "The Guardian",
    "the-washington-post"
    "abc-news",
    "cbs-news",
    "bbc-news",
}