SCHOOLS = {
    "mit.edu": {"school": "Massachusetts Institute of Technology (MIT)", "type": "university", "rank": 1},
    "cam.ac.uk": {"school": "University of Cambridge", "type": "university", "rank": 2},
    "ox.ac.uk": {"school": "University of Oxford", "type": "university", "rank": 3},
    "harvard.edu": {"school": "Harvard University", "type": "university", "rank": 4},
    "stanford.edu": {"school": "Stanford University", "type": "university", "rank": 5},
    "imperial.ac.uk": {"school": "Imperial College London", "type": "university", "rank": 6},
    "ethz.ch": {"school": "Swiss Federal Institute of Technology", "type": "university", "rank": 7},
    "nus.edu.sg": {"school": "National University of Singapore", "type": "university", "rank": 8},
    "ucl.ac.uk": {"school": "University College London (UCL)", "type": "university", "rank": 9},
    "berkeley.edu": {"school": "University of California, Berkeley", "type": "university", "rank": 10},
    "uchicago.edu": {"school": "University of Chicago", "type": "university", "rank": 11},
    "upenn.edu": {"school": "University of Pennsylvania", "type": "university", "rank": 12},
    "cornell.edu": {"school": "Cornell University", "type": "university", "rank": 13},
    "unimelb.edu.au": {"school": "University of Melbourne", "type": "university", "rank": 14},
    "caltech.edu": {"school": "California Institute of Technology (CalTech)", "type": "university", "rank": 15},
    "yale.edu": {"school": "Yale University", "type": "university", "rank": 16},
    "pku.edu.cn": {"school": "Peking University", "type": "university", "rank": 17},
    "princeton.edu": {"school": "Princeton University", "type": "university", "rank": 17},
    "unsw.edu.au": {"school": "University of New South Wales (UNSW Sydney)", "type": "university", "rank": 19},
    "sydney.edu.au": {"school": "University of Sydney", "type": "university", "rank": 19},
    "utoronto.ca": {"school": "University of Toronto", "type": "university", "rank": 21},
    "ed.ac.uk": {"school": "University of Edinburgh", "type": "university", "rank": 22},
    "columbia.edu": {"school": "Columbia University", "type": "university", "rank": 23},
    "psl.eu": {"school": "Université PSL", "type": "university", "rank": 24},
    "tsinghua.edu.cn": {"school": "Tsinghua University", "type": "university", "rank": 25},
    "ntu.edu.sg": {"school": "Nanyan Technological University, Singapore (TNU)", "type": "university", "rank": 26},
    "hku.hk": {"school": "University of Hong Kong", "type": "university", "rank": 26},
    "u-tokyo.ac.jp": {"school": "University of Tokyo", "type": "university", "rank": 28},
    "mcgill.ca": {"school": "McGill University", "type": "university", "rank": 30},
    "manchester.ac.uk": {"school": "University of Manchester", "type": "university", "rank": 32},
    "anu.edu.au": {"school": "Australian National University", "type": "university", "rank": 34},
    "ubc.ca": {"school": "University of British Columbia", "type": "university", "rank": 34},
    "epfl.ch": {"school": "Ecole Polytechnique Fédérale de Lausanne (EPFL)", "type": "university", "rank": 36},
    "tum.de": {"school": "Technical University of Munich", "type": "university", "rank": 37},
    "ip-paris.fr": {"school": "Institut Polytechnique de Paris", "type": "university", "rank": 38},
    "snu.ac.kr": {"school": "Seoul National University", "type": "university", "rank": 41},
    "monash.edu": {"school": "Monash University", "type": "university", "rank": 42},
    "zju.edu.cn": {"school": "Zhejiang University", "type": "university", "rank": 44},
    "lse.ac.uk": {"school": "London School of Economics (LSE)", "type": "university", "rank": 45},
    "kyoto-u.ac.jp": {"school": "Kyoto University", "type": "university", "rank": 46},
    "tudelft.nl": {"school": "Delft University of Technology", "type": "university", "rank": 47},
    "northwestern.edu": {"school": "Northwestern University", "type": "university", "rank": 47},
    "uva.nl": {"school": "University of Amsterdam", "type": "university", "rank": 53},
    "lmu.de": {"school": "LMU Munchen", "type": "university", "rank": 54},
    "bristol.ac.uk": {"school": "University of Bristol", "type": "university", "rank": 55},
    "kaist.ac.kr": {"school": "Korea Advanced Institute of Science & Technology", "type": "university", "rank": 56},
    "duke.edu": {"school": "Duke University", "type": "university", "rank": 57},
    "rice.edu": {"school": "Rice University", "type": "university", "rank": 57},
    "sorbonne-universite.fr": {"school": "Sorbonne University", "type": "university", "rank": 59},
    "kuleuven.be": {"school": "KU Leuven", "type": "university", "rank": 61},
    "um.edu.my": {"school": "Universiti Malaya", "type": "university", "rank": 65},
    "auckland.ac.nz": {"school": "University of Auckland", "type": "university", "rank": 68},
    "ntu.edu.tw": {"school": "National Taiwan University (NTU)", "type": "university", "rank": 69},
    "kth.se": {"school": "KTH Royal Institute of Technology", "type": "university", "rank": 73},
    "tcd.le": {"school": "Trinity College Dublin", "type": "university", "rank": 81},
    "usp.br": {"school": "Universidade de São Paulo", "type": "university", "rank": 85},
    "msu.ru": {"school": "Lomonosov Moscow State University", "type": "university", "rank": 87},
    "uni-heidelberg.de": {"school": "Universität Heidelberg", "type": "university", "rank": 87},
    "unam.mx": {"school": "UNAM", "type": "university", "rank": 93},
    "uba.ar": {"school": "Universidad de Buenos Aires (UBA)", "type": "university", "rank": 95},
    "ub.edu": {"school": "University of Barcelona", "type": "university", "rank": 100},
    "unibo.it": {"school": "University of Bologna", "type": "university", "rank": 100},
    "qu.edu.qa": {"school": "Qatar University", "type": "university", "rank": 100},
    "kau.edu.sa": {"school": "King Abdulaziz University", "type": "university", "rank": 100},
    "ku.ac.ae": {"school": "Khalifa University", "type": "university", "rank": 100},
    "kaust.edu.sa": {"school": "King Abdullah University of Science and Technology (KAUST)", "type": "university", "rank": 100},
    "zewailcity.edu.eg": {"school": "Zewail City of Science and Technology", "type": "university", "rank": 100},
    "sharjah.ac.ae": {"school": "University of Sharjah", "type": "university", "rank": 100},
    "ksu.edu.sa": {"school": "King Saud University", "type": "university", "rank": 100},
    "uct.ac.za": {"school": "University of Cape Town", "type": "university", "rank": 100},
    "wits.ac.za": {"school": "University of Witwatersrand", "type": "university", "rank": 100},
    "ui.edu.ng": {"school": "University of Ibadan", "type": "university", "rank": 100},
    "cu.edu.eg": {"school": "Cairo University", "type": "university", "rank": 100},
    "uj.ac.za": {"school": "University of Johannesburg", "type": "university", "rank": 100},
    "mans.edu.eg": {"school": "Mansoura University", "type": "university", "rank": 100},
    "mu.edu.et": {"school": "Mekelle University", "type": "university", "rank": 100},
    "aau.edu.et": {"school": "Addis Ababa University", "type": "university", "rank": 100},
    "unza.zm": {"school": "University of Zambia", "type": "university", "rank": 100},
    "mak.ac.ug": {"school": "Makerere University", "type": "university", "rank": 100},
    "uonbi.ac.ke": {"school": "University of Nairobi", "type": "university", "rank": 100},
    "univh2c.ma": {"school": "Hassan II University of Casablanca", "type": "university", "rank": 100},
    "ump.ma": {"school": "Mohammed First University of Oujda", "type": "university", "rank": 100},
    "ug.edu.gh": {"school": "University of Ghana", "type": "university", "rank": 100},
    "utm.rnu.tn": {"school": "Universite de Tunis-El-Manar", "type": "university", "rank": 100},
    "tau.ac.il": {"school": "Tel Aviv University", "type": "university", "rank": 100},
    "tums.ac.ir": {"school": "Tehran University of Medical Sciences", "type": "university", "rank": 100},
    "weizmann.ac.il": {"school": "Weizmann Institute of Science", "type": "university", "rank": 100},
    "technion.ac.il": {"school": "Technion - Israel Institute of Technology", "type": "university", "rank": 100},
    "huji.ac.il": {"school": "Hebrew University of Jerusalem", "type": "university", "rank": 100},
    "aau.edu.jo": {"school": "Amman Arab University", "type": "university", "rank": 100},
    "ut.ac.ir": {"school": "Tehran University", "type": "university", "rank": 100},
    "bilkent.edu.tr": {"school": "Bilkent University", "type": "university", "rank": 100},
    "hacettepe.edu.tr": {"school": "Hacettepe University", "type": "university", "rank": 100},
    "ul.edu.lb": {"school": "Lebanese University", "type": "university", "rank": 100},
    "ariel.ac.il": {"school": "Ariel University", "type": "university", "rank": 100},
    "alquds.edu": {"school": "Al-Quds University", "type": "university", "rank": 100},
    "tishreen.edu.sy": {"school": "Tishreen University", "type": "university", "rank": 100},
    "uoitc.edu.iq": {"school": "University of Information Technology and Communication (UolTC)", "type": "university", "rank": 100},
    "gmail.com": {"school": "World", "type": "public", "rank": -1},
}