from django.urls import path
from rest_framework import routers
from django.conf.urls import include
from . import views

urlpatterns = [
    path("login/", views.login),
    path("signup/", views.signup),
    path("getProfile/", views.getProfile),
    path("search/", views.search),
    path("request/", views.request),
    path("unrequest/", views.unrequest),
    path("getProfileOf/", views.getProfileOf),
    path("getRequesting/", views.getRequesting),
    path("getRequested/", views.getRequested),
    path("getMatches/", views.getMatches),
    path("getChats/", views.getChats),
    path("getM/", views.getM),
    path("sendM/", views.sendM),
    path("sendMImage/", views.sendMImage),
    path("call/", views.call),
    path("getCall/", views.getCall),
    path("acceptCall/", views.acceptCall),
    path("endCall/", views.endCall),
    path("getLines/", views.getLines),
    path("logout/", views.logout),
    path("startSearch/", views.startSearch),
    path("cancelSearch/", views.cancelSearch),
    path("verifyCity/", views.verifyCity),
    path("profileImage/", views.profileImage),
    path("setProfile/", views.setProfile),
    path("setName/", views.setName),
    path("setBio/", views.setBio),
    path("setHobbies/", views.setHobbies),
    path("setCountry/", views.setCountry),
    path("setCity/", views.setCity),
    path("getRequests/", views.getRequests),
    path("denyRe/", views.denyRe),
    path("acceptRe/", views.acceptRe),
    path("cancelMatch/", views.cancelMatch),
    path("getFriends/", views.getFriends),
    path("getPastCalls/", views.getPastCalls),
    path("report/", views.report),
    path("unreport/", views.unreport),
    path("unfriend/", views.unfriend),
    path("setAllCord", views.setAllCord),
    path("endMatch/", views.endMatch),
    path("getNews/", views.getNews),
    path("checkEmail/", views.checkEmail),
    path("confirmEmail/", views.confirmEmail),
    path("setUser/", views.setUser),
    path("updatePrev", views.updatePrev),
    path("createGroup/", views.createGroup),
    path("react/", views.react),
    path("writeNews/", views.writeNews),
    path("postNewColab/", views.postNewColab),
    path("newColabMedia/", views.newColabMedia),
    path("getColabs/", views.getColabs),
    path("getGroup/", views.getGroup),
    path("addToGroup/", views.addToGroup),
    path("setGroupName/", views.setGroupName),
    path("postNewComment/", views.postNewComment),
    path("postCommentReply/", views.postCommentReply),
    path("trainModel/", views.trainKModel),
    path("getColabsOf/", views.getColabsOf),
    path("update/", views.update),
]