# Generated by Django 4.0.4 on 2023-08-14 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first', models.CharField(blank=True, max_length=250)),
                ('last', models.CharField(blank=True, max_length=250)),
                ('token', models.CharField(blank=True, max_length=350)),
                ('image', models.FileField(blank=True, upload_to='images/profileImages/')),
                ('network', models.ManyToManyField(blank=True, related_name='+', to='home.country')),
            ],
        ),
    ]
