# Generated by Django 4.0.4 on 2023-08-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_dob_profile_setup_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
