# Generated by Django 4.0.4 on 2023-08-19 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_profile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed+', to=settings.AUTH_USER_MODEL)),
                ('requesting', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ing+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.request'),
        ),
    ]
