# Generated by Django 4.0.4 on 2023-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pushtoken_profile_pushtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.chat'),
        ),
    ]
