# Generated by Django 4.0.4 on 2023-08-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_profile_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, upload_to='images/chatImages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=250)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.reaction'),
        ),
    ]
