# Generated by Django 4.0.4 on 2023-08-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='call',
        ),
    ]
