# Generated by Django 4.0.4 on 2023-08-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_profile_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='call',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.call'),
        ),
    ]
