# Generated by Django 4.0.4 on 2023-09-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_hackerip_remove_pastcall_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pastcall',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
