# Generated by Django 4.0.4 on 2023-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_group_profile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schoolType',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
