# Generated by Django 4.0.4 on 2023-10-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
