# Generated by Django 4.0.4 on 2023-10-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_profile_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('channel', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('called', models.ManyToManyField(default=None, null=True, related_name='ed+', to=settings.AUTH_USER_MODEL)),
                ('calling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
