# Generated by Django 4.0.4 on 2023-10-30 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_groupcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcall',
            name='called',
        ),
        migrations.AddField(
            model_name='groupcall',
            name='members',
            field=models.ManyToManyField(default=None, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
