# Generated by Django 4.0.4 on 2023-11-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_groupcall_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groupCall',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.groupcall'),
        ),
    ]
