# Generated by Django 4.0.4 on 2023-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_profile_groupcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='searching',
            name='number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
