# Generated by Django 4.0.4 on 2023-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_news_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='over',
            field=models.BooleanField(default=False),
        ),
    ]
