# Generated by Django 4.0.4 on 2023-12-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_call_called_alter_call_calling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcall',
            name='calling',
        ),
    ]
