# Generated by Django 4.0.4 on 2023-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_groupcall_calling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, upload_to='colab/')),
            ],
        ),
        migrations.RemoveField(
            model_name='colab',
            name='media',
        ),
        migrations.AddField(
            model_name='colab',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.media'),
        ),
    ]
