# Generated by Django 4.0.4 on 2023-12-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_media_remove_colab_media_colab_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='colab',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
