# Generated by Django 4.0.4 on 2023-12-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_colab_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='media',
            name='mediaType',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
