# Generated by Django 4.0.4 on 2023-12-22 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_media_duration_media_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
