# Generated by Django 4.0.4 on 2023-12-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_media_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
