# Generated by Django 4.0.4 on 2023-12-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_group_colab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='hasName',
            field=models.BooleanField(default=False),
        ),
    ]
