# Generated by Django 4.0.4 on 2024-01-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(default=None, to='home.comment'),
        ),
    ]
