# Generated by Django 4.0.4 on 2024-01-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='home.comment'),
        ),
    ]
