# Generated by Django 4.0.4 on 2024-02-28 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0055_news_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
