# Generated by Django 4.0.4 on 2024-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_news_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
